[mysql]
host = "eshows-1.czzecscahytf.us-east-2.rds.amazonaws.com"
port = 6303
database = "eshows"
username = "relatorios@eshows.com.br"
password = "R96170928641285"

[general]
SECRET_KEY = "eshowssecretkey"